export enum ModuleKey {
  INVOICING = 'INVOICING',
  CHART_OF_ACCOUNTS = 'CHART_OF_ACCOUNTS',
  JOURNAL_ENTRIES = 'JOURNAL_ENTRIES',
  GENERAL_LEDGER = 'GENERAL_LEDGER',
  FINANCIAL_STATEMENTS = 'FINANCIAL_STATEMENTS',
  BANK_RECONCILIATION = 'BANK_RECONCILIATION',
  SRI_REPORTS = 'SRI_REPORTS',
}
